name: Build and Test - Client

concurrency:
  group: '${{ github.head_ref || github.ref }} Client'
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

# TODO: run go tests
jobs:
  web_test:
    name: Web Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run action lint

      - name: Build Web App
        run: npm run action www/build

      - name: Test Web App
        run: npm run action www/test

      - uses: codecov/codecov-action@v3
        with:
          files: ./output/coverage/www/coverage-final.json
          flags: unittests, www

  windows_debug_build:
    name: Windows Debug Build
    runs-on: windows-2019
    timeout-minutes: 20
    needs: web_test
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: '${{ github.workspace }}/go.mod'

      - name: Build Windows Client
        run: npm run action electron/build windows
